"""
Claude Review Loop — post-generation quote review via Claude API.

Calls Claude to review a completed PricedQuote for:
- Material/profile mismatches
- Unreasonable quantities or costs
- Missing structural items
- Labor hour sanity

Graceful fallback when ANTHROPIC_API_KEY is not set.
"""

import json
import logging
import os
from typing import Optional

import httpx

logger = logging.getLogger(__name__)

CLAUDE_REVIEW_MODEL = os.environ.get("CLAUDE_REVIEW_MODEL", "claude-sonnet-4-20250514")
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages"

SYSTEM_PROMPT = """You are a senior metal fabrication estimator reviewing a quote generated by an automated quoting system. You have 20+ years of experience in structural steel, ornamental iron, and custom fabrication.

Review the quote for:
1. MATERIAL ISSUES: Wrong profiles for the application, missing structural members, undersized beams/posts
2. QUANTITY ISSUES: Unreasonable material quantities, too many/few fasteners or consumables
3. COST ISSUES: Line items that seem too expensive or too cheap for the described work
4. LABOR ISSUES: Hours that don't match the scope (too high or too low for the work described)
5. SAFETY ISSUES: Missing items that are structurally required (e.g., missing posts, undersized members for load)

Return your review as JSON with this exact structure:
{
    "issues": ["Critical problems that MUST be fixed before sending this quote"],
    "warnings": ["Potential problems worth checking but not blocking"],
    "suggestions": ["Optional improvements to make the quote better"],
    "score": 85
}

Score is 0-100 where:
- 90-100: Production ready, send to customer
- 70-89: Minor issues, review recommended
- 50-69: Significant issues, needs revision
- Below 50: Major problems, do not send

Be specific. Reference actual line items, profiles, and numbers from the quote.
Keep each issue/warning/suggestion to one concise sentence.
Return ONLY valid JSON, no markdown fences or other text."""


def review_quote(quote_data: dict, fields: dict) -> dict:
    """
    Review a completed quote using Claude API.

    Args:
        quote_data: The PricedQuote dict from Stage 5
        fields: The session fields (job description, dimensions, etc.)

    Returns:
        dict with keys: issues, warnings, suggestions, score, reviewed
        If API key not set or call fails, returns graceful fallback.
    """
    api_key = os.environ.get("ANTHROPIC_API_KEY", "") or ANTHROPIC_API_KEY
    if not api_key:
        return {
            "issues": [],
            "warnings": [],
            "suggestions": ["Claude review unavailable — ANTHROPIC_API_KEY not configured."],
            "score": None,
            "reviewed": False,
        }

    # Build the review prompt
    job_type = quote_data.get("job_type", fields.get("job_type", "unknown"))
    description = fields.get("description", "No description provided")

    # Summarize the quote for review
    materials_summary = []
    for item in quote_data.get("materials", []):
        materials_summary.append(
            "- %s | profile: %s | qty: %s | $%.2f"
            % (item.get("description", "?"),
               item.get("profile", "?"),
               item.get("quantity", "?"),
               item.get("line_total", 0))
        )

    labor_summary = []
    for proc in quote_data.get("labor", []):
        labor_summary.append(
            "- %s: %.2f hrs @ $%.2f/hr"
            % (proc.get("process", "?"),
               proc.get("hours", 0),
               proc.get("rate", 0))
        )

    consumables_summary = []
    for item in quote_data.get("consumables", []):
        consumables_summary.append(
            "- %s | $%.2f"
            % (item.get("description", "?"), item.get("line_total", 0))
        )

    user_prompt = """Review this %s quote:

JOB DESCRIPTION: %s

MATERIALS (%d items, subtotal $%.2f):
%s

LABOR (%d processes, %.1f total hours, subtotal $%.2f):
%s

CONSUMABLES (%d items, subtotal $%.2f):
%s

FINISHING: %s — $%.2f

SUBTOTAL: $%.2f
TOTAL (with %d%% markup): $%.2f

ASSUMPTIONS:
%s""" % (
        job_type,
        description,
        len(quote_data.get("materials", [])),
        quote_data.get("material_subtotal", 0),
        "\n".join(materials_summary) or "None",
        len(quote_data.get("labor", [])),
        sum(p.get("hours", 0) for p in quote_data.get("labor", [])),
        quote_data.get("labor_subtotal", 0),
        "\n".join(labor_summary) or "None",
        len(quote_data.get("consumables", [])),
        quote_data.get("consumable_subtotal", 0),
        "\n".join(consumables_summary) or "None",
        quote_data.get("finishing", {}).get("method", "raw"),
        quote_data.get("finishing_subtotal", 0),
        quote_data.get("subtotal", 0),
        quote_data.get("selected_markup_pct", 0),
        quote_data.get("total", 0),
        "\n".join("- %s" % a for a in quote_data.get("assumptions", [])) or "None",
    )

    try:
        return _call_claude_api(api_key, user_prompt)
    except Exception as e:
        logger.warning("Claude review failed: %s", str(e))
        return {
            "issues": [],
            "warnings": [],
            "suggestions": ["Claude review failed: %s" % str(e)],
            "score": None,
            "reviewed": False,
        }


def _call_claude_api(api_key: str, user_prompt: str) -> dict:
    """Make the actual API call to Claude."""
    headers = {
        "x-api-key": api_key,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
    }

    payload = {
        "model": CLAUDE_REVIEW_MODEL,
        "max_tokens": 1024,
        "system": SYSTEM_PROMPT,
        "messages": [
            {"role": "user", "content": user_prompt}
        ],
    }

    with httpx.Client(timeout=30.0) as client:
        response = client.post(ANTHROPIC_API_URL, headers=headers, json=payload)
        response.raise_for_status()

    result = response.json()
    content_text = result.get("content", [{}])[0].get("text", "{}")
    return _parse_review(content_text)


def _parse_review(text: str) -> dict:
    """Parse Claude's JSON response into a structured review dict."""
    # Strip markdown fences if present
    cleaned = text.strip()
    if cleaned.startswith("```"):
        # Remove opening fence (with optional language tag)
        first_newline = cleaned.index("\n")
        cleaned = cleaned[first_newline + 1:]
    if cleaned.endswith("```"):
        cleaned = cleaned[:-3].strip()

    try:
        data = json.loads(cleaned)
    except (json.JSONDecodeError, ValueError):
        return {
            "issues": [],
            "warnings": ["Could not parse Claude review response."],
            "suggestions": [],
            "score": None,
            "reviewed": False,
        }

    return {
        "issues": data.get("issues", []),
        "warnings": data.get("warnings", []),
        "suggestions": data.get("suggestions", []),
        "score": data.get("score"),
        "reviewed": True,
    }
