"""v2 foundation: add users, auth_tokens, quote_sessions, hardware_items, historical_actuals; extend quotes; job_type to varchar

Revision ID: 82694c65cf42
Revises: 
Create Date: 2026-02-27 13:23:57.904631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82694c65cf42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('hardware_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('mcmaster_part', sa.String(), nullable=True),
    sa.Column('mcmaster_price', sa.Float(), nullable=True),
    sa.Column('mcmaster_url', sa.String(), nullable=True),
    sa.Column('alt1_supplier', sa.String(), nullable=True),
    sa.Column('alt1_price', sa.Float(), nullable=True),
    sa.Column('alt1_url', sa.String(), nullable=True),
    sa.Column('alt2_supplier', sa.String(), nullable=True),
    sa.Column('alt2_price', sa.Float(), nullable=True),
    sa.Column('alt2_url', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hardware_items_id'), 'hardware_items', ['id'], unique=False)
    op.create_table('material_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.Enum('MILD_STEEL', 'STAINLESS_304', 'STAINLESS_316', 'ALUMINUM_6061', 'ALUMINUM_5052', 'DOM_TUBING', 'SQUARE_TUBING', 'ANGLE_IRON', 'FLAT_BAR', 'PLATE', 'CHANNEL', name='materialtype'), nullable=False),
    sa.Column('price_per_lb', sa.Float(), nullable=True),
    sa.Column('price_per_sqft', sa.Float(), nullable=True),
    sa.Column('price_per_foot', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_type')
    )
    op.create_index(op.f('ix_material_prices_id'), 'material_prices', ['id'], unique=False)
    op.create_table('process_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_type', sa.Enum('LAYOUT', 'CUTTING', 'CNC_PLASMA', 'CNC_ROUTER', 'WELDING', 'TIG_WELDING', 'GRINDING', 'DRILLING', 'BENDING', 'ASSEMBLY', 'DESIGN', 'FIELD_INSTALL', 'PROJECT_MANAGEMENT', 'POWDER_COAT', 'PAINT', name='processtype'), nullable=False),
    sa.Column('rate_per_hour', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_type')
    )
    op.create_index(op.f('ix_process_rates_id'), 'process_rates', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_provisional', sa.Boolean(), nullable=True),
    sa.Column('shop_name', sa.String(), nullable=True),
    sa.Column('shop_address', sa.Text(), nullable=True),
    sa.Column('shop_phone', sa.String(), nullable=True),
    sa.Column('shop_email', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('rate_inshop', sa.Float(), nullable=True),
    sa.Column('rate_onsite', sa.Float(), nullable=True),
    sa.Column('markup_default', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_tokens_id'), 'auth_tokens', ['id'], unique=False)
    op.create_table('quote_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('messages_json', sa.JSON(), nullable=True),
    sa.Column('photo_urls', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_number', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'DECLINED', name='quotestatus'), nullable=True),
    sa.Column('project_description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('labor_rate', sa.Float(), nullable=True),
    sa.Column('waste_factor', sa.Float(), nullable=True),
    sa.Column('material_markup_pct', sa.Float(), nullable=True),
    sa.Column('stainless_multiplier', sa.Float(), nullable=True),
    sa.Column('contingency_pct', sa.Float(), nullable=True),
    sa.Column('profit_margin_pct', sa.Float(), nullable=True),
    sa.Column('markup', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('valid_days', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('inputs_json', sa.JSON(), nullable=True),
    sa.Column('outputs_json', sa.JSON(), nullable=True),
    sa.Column('selected_markup_pct', sa.Integer(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_number')
    )
    op.create_index(op.f('ix_quotes_id'), 'quotes', ['id'], unique=False)
    op.create_table('historical_actuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('actual_hours_by_process', sa.JSON(), nullable=True),
    sa.Column('actual_material_cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('variance_pct', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_actuals_id'), 'historical_actuals', ['id'], unique=False)
    op.create_table('quote_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('material_type', sa.Enum('MILD_STEEL', 'STAINLESS_304', 'STAINLESS_316', 'ALUMINUM_6061', 'ALUMINUM_5052', 'DOM_TUBING', 'SQUARE_TUBING', 'ANGLE_IRON', 'FLAT_BAR', 'PLATE', 'CHANNEL', name='materialtype'), nullable=True),
    sa.Column('process_type', sa.Enum('LAYOUT', 'CUTTING', 'CNC_PLASMA', 'CNC_ROUTER', 'WELDING', 'TIG_WELDING', 'GRINDING', 'DRILLING', 'BENDING', 'ASSEMBLY', 'DESIGN', 'FIELD_INSTALL', 'PROJECT_MANAGEMENT', 'POWDER_COAT', 'PAINT', name='processtype'), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('dim_length', sa.Float(), nullable=True),
    sa.Column('dim_width', sa.Float(), nullable=True),
    sa.Column('dim_thickness', sa.Float(), nullable=True),
    sa.Column('weight_lbs', sa.Float(), nullable=True),
    sa.Column('waste_factor', sa.Float(), nullable=True),
    sa.Column('material_cost', sa.Float(), nullable=True),
    sa.Column('labor_hours', sa.Float(), nullable=True),
    sa.Column('process_rate_override', sa.Float(), nullable=True),
    sa.Column('labor_cost', sa.Float(), nullable=True),
    sa.Column('outsourced', sa.Boolean(), nullable=True),
    sa.Column('outsource_service', sa.String(), nullable=True),
    sa.Column('outsource_rate_per_sqft', sa.Float(), nullable=True),
    sa.Column('sq_ft', sa.Float(), nullable=True),
    sa.Column('line_total', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_line_items_id'), 'quote_line_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_line_items_id'), table_name='quote_line_items')
    op.drop_table('quote_line_items')
    op.drop_index(op.f('ix_historical_actuals_id'), table_name='historical_actuals')
    op.drop_table('historical_actuals')
    op.drop_index(op.f('ix_quotes_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_table('quote_sessions')
    op.drop_index(op.f('ix_auth_tokens_id'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_process_rates_id'), table_name='process_rates')
    op.drop_table('process_rates')
    op.drop_index(op.f('ix_material_prices_id'), table_name='material_prices')
    op.drop_table('material_prices')
    op.drop_index(op.f('ix_hardware_items_id'), table_name='hardware_items')
    op.drop_table('hardware_items')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
